### ISSUE TITLE
Create & deploy MoonPortfolio Server

### ISSUE THREAD

**Issue by leongaban** [leongaban/moon-portfolio-app#2]
From ZTM tutorial: https://academy.zerotomastery.io/courses/697434/lectures/12671530

- [x] Finish ZTM server lectures
- [x] Create all required routes
- [x] Test locally
- [x] Connect to database
- [x] Deploy to Render
- [x] Deploy FE to Netlify

**Comment by leongaban** [comment]
signin and register from frontend hitting background routes on localhost

**Comment by leongaban** [comment]
- Middlewares & Controllers added
- Deploying to Render.com now
- Next is deploying DB to render and connecting both
